import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <main className="relative container w-full mx-auto scroll-py-20">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
